export class DataManager {
    public selectedFluffyBag: string = '';
}

export enum FluffyBagDetailId {
    fluffyOne = "fluffyBagUno",
    fluffyTwo = "fluffyBagDue",
    fluffyThree = "fluffyBagTre",
    fluffyFour = "fluffyBagQuattro",
    fluffyFive = "fluffyBagCinque",
    fluffySix = "fluffyBagSei",
    fluffySeven = "fluffyBagSette",
    fluffyEight = 'fluffyBagOtto',
    fluffyNine = "fluffyBagNove",
    fluffyTen = "fluffyBagTen",
    fluffyEleven = 'fluffyBagUndici',
    fluffyTwelve = 'fluffyBagDodici',
    fluffyThirteen = 'fluffyBagTredici',
    fluffyFourteen = "fluffyBagQuattordici",
    fluffyFifteen = "fluffyBagQuindici",
    fluffySixteen = "fluffyBagSedici",
    fluffySeventeen = "fluffyBagDiciassette",
    fluffyEigtheen = "fluffyBagDiciotto",
    fluffyNineteen = "fluffyBagDiciannove",
    fluffyTwenty = "fluffyBagVenti",
    fluffyTwentyOne = "fluffyVentuno",
    fluffyTwentyThree = "fluffyVentitre",
    fluffyTwentyFour = "fluffyVentiquattro",
    fluffyTwentyFive = "fluffyVenticinque",
    fluffyTwentySix = "fluffyVentisei",

    fluffyThirty = "fluffyTrenta",
    fluffyThirtyOne = "fluffyTrentuno",
    fluffyThirtyTwo = "fluffyTrentadue",
    fluffyThirtyThree = "fluffyTrentatre",
    fluffyThirtyFour = "fluffyTrentaquattro",
    fluffyThirtyFive = "fluffyTrentacinque",
    fluffyThirtySix = "fluffyTrentasei",
    fluffyThirtySeven = "fluffyTrentasette",
    fluffyThirtyEight = "fluffyTrentotto",
    fluffyThirtyNine = "fluffyTrentanove",
    fluffyForty = "fluffyQuaranta",
  }